### ISSUE TITLE
DB Password with ampersand causes error on Put

### ISSUE THREAD

**Issue by tonegolf71** [Space48/magedbm2#31]
When attempting to run `put` with a database that had a password with an ampersand (&) in it, I received the following error.

```
[alert] There was an error in one of the commands -- stopping others.
Failed to create a database backup file: There was an error exporting the database: sh: --port=3307: command not found
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
```

This is because the password gets output to the mysqldump command directly and the & causes the commandline to see the rest of the string as a new command.

e.g.

` mysqldump --single-transaction --quick --host=127.0.0.1 --user=magento_user --password=uy7j1gdf6& --port=3307 --no-data --add-drop-table`...etc

Some escaping is likely needed.

**Comment by punkstar** [comment]
I think these are missing [escapeshellarg](https://www.php.net/escapeshellarg) calls here: https://github.com/Space48/magedbm2/blob/master/src/Service/Database/Shell.php#L208:L213
