### ISSUE TITLE
view-config command does not work

### ISSUE THREAD

**Issue by jakeworrall** [Space48/magedbm2#49]
When I run the command `magedbm2 view-config` (documented in the README) the output is `Command "view-config" is not defined.`.

I am running version `2.0.2`.

**Comment by punkstar** [comment]
Ah, this command isn't released yet. Added required versions in the readme with #51. You can see the currently unreleased features on `master` at https://github.com/Space48/magedbm2/blob/master/CHANGELOG.md under the "Unreleased" heading.
