### ISSUE TITLE
Local config incorrectly overwrites default config

### ISSUE THREAD

**Issue by jakeworrall** [Space48/magedbm2#50]
In my local config file I created a table group with a separate name to any of those in the default magedbm2 config file.

With this file in place I saw that the first table group in the default config file, `admin` was overwritten by my table group, despite them having different names.

Running the `put` command with `--strip="@admin"` did not strip any admin tables as that table group did not exist.

**Comment by punkstar** [comment]
Good spot! Added a test for this on https://github.com/Space48/magedbm2/tree/local-config-override-array-50 (https://github.com/Space48/magedbm2/commit/d68c2bdadca322445652246505d8d18025e1c064) but have not fixed yet.

**Comment by punkstar** [comment]
Perhaps moving the logic out to https://github.com/lukascivil/TreeWalker, or something similar would be useful. Merging of this kind of structure should be well-trodden ground.
